### ISSUE TITLE
Any public roadmap?

### ISSUE THREAD

**Issue by bamorim** [stone-co/the-amazing-ledger#13]
Thanks for making this public. I took a look at the data modeling and looks good.
I think it is great to have this as a kind of shared effort.

However, it took me a while to realize that the use cases are not even implemented yet. With that in mind, I have two questions:

- Can we have a public roadmap about what is missing and what will be implemented yet and when?
- Can we add a disclaimer on the readme to state that it is still pre-release/in progress?

I think having these two things would help attract external collaborators.

Thanks

**Comment by alexgarzao** [comment]
Hello @bamorim . First of all, sorry for the great delay in answer.

We will love to share the effort to do this project. Any contribution is very welcome :-)

About the roadmap. Could you take a look at this PR? https://github.com/stone-co/the-amazing-ledger/pull/23/files

About the disclaimer on the readme, nice, we will do.

Thanks.

**Comment by bamorim** [comment]
@alexgarzao thanks for the reply nevertheless. I'll take a look.
