### ISSUE TITLE
Proposal: Add a proto linter

### ISSUE THREAD

**Issue by alexrios** [stone-co/the-amazing-ledger#22]
Since the project is starting to use gRPC, what do you guys think about to adopt a linter like [buf](https://buf.build/)?

**Comment by alexgarzao** [comment]
It's a very good idea :-)

I took a look now at https://golangci-lint.run/usage/linters/, but there isn't one to deal with proto.

Could you make a PR using 'buf', as you suggested?

**Comment by alexrios** [comment]
Sure! I'm just waiting the PR #21 to start work on it.

**Comment by alexgarzao** [comment]
Nice!

#21 was merged. Thanks for all of your contribution on #21 :-)

**Comment by alexrios** [comment]
PTAL? #40

**Comment by alexgarzao** [comment]
Very nice! #40 is very fine, IMHO :-)
