### ISSUE TITLE
Linter for the system architecture

### ISSUE THREAD

**Issue by alexgarzao** [stone-co/the-amazing-ledger#31]
As suggested, we will use this linter: https://github.com/resotto/gochk

**Comment by alexandreliberato** [comment]
@alexgarzao Can you assign this issue to me?

**Comment by alexgarzao** [comment]
Wellcome @alexandreliberato :-)

Sure!

**Comment by alexandreliberato** [comment]
I was studying the tool, so I will make a summary description of how it works and what I'm going to do on this branch.

It's a static analysis tool, and it must be installed on our pipeline to be used.
It will check the dependency order (configured by us) of the import paths and decide if it is valid or not.

e.g:  "dependencyOrders": ["external", "adapter", "application", "domain"],

So now I will analyze our paths to see how we should configure this dependency order and check how it works on github to install this tool.

**Comment by alexandreliberato** [comment]
Actual directory tree:
![image](https://user-images.githubusercontent.com/300424/100171974-16fc1480-2ea6-11eb-9d78-5ce9d6504940.png)

**Comment by alexandreliberato** [comment]
I would like to understand better the package system.
We are going to use a clean architecture based architecture?

I would suggest this dependency order at first:
 "dependencyOrders": ["clients", "gateways", "command-handler"],
                                       0                1                   2
                                     outer                  >>>                        inner
e.g:

   If a file with path "command-handler/domain/ledger/accountsUsecase.go" use a import like "gateways/http/api", the index of the file is 2 and the index of the import path is 1. So it violates the dependency order: 1 (index os import path) < 2 (index of file)

But later, maybe, we could change or packaging to something more clear like this:
 "dependencyOrders": ["adapters", "application"],

**Comment by alexgarzao** [comment]
Wecolme to the team @alexandreliberato :-)

Yep, the idea is to use a clean arch. At this time, we know that we need to improve a lot of things rsrsrs.

Some points that we know must be fixed:

- Everything inside /clients is a SDK and will be moved to another repository
- command-handler is useless, and is our idea move everything inside /pkg/command-handler/domain to /pkg/domain
- Everything inside /pkg/command-handler/domain/ledger will be moved to /pkg/command-handler/domain

About your example. Yes, if accountsUsecase import something from gateways, it's a mistake.

About the term "adapters". In clean arch, the term is gateways (https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html). Adapters is a term from hex arch.

**Comment by alexrios** [comment]
> Everything inside /clients is a SDK and will be moved to another repository
It's a good move. I endorse it 💡

Also we could start thinking about separating the _proto_ definitions, since the ledger server is one possible (and official) server implementation - as client is as well.

**Comment by alexgarzao** [comment]
| Also we could start thinking about separating the proto definitions, since the ledger server is one possible (and official) server implementation - as client is as well.

I agree :-)
