### ISSUE TITLE
Get the history of an account (operations)

### ISSUE THREAD

**Issue by alexgarzao** [stone-co/the-amazing-ledger#32]
Given an account and a date range, returns the operation's history of that account. Date must be expressed in [ISO 8601 format](https://en.wikipedia.org/wiki/ISO_8601): "YYYY-MM-DD".

Example: Call to get the history of the account "aaa:bbb:ccc:ddd/fff", during February 2020 and April 2020. StartDate is equal to "2020-02-01" and EndDate is equal to "2020-03-31".

Representation of the return in JSON format, just as an example:

```
{
    "account": "aaa:bbb:ccc:ddd/fff",
    "total_debit": 123,
    "total_credit": 456,
    "entries": [
        {
            "operation": "debit",
            "amount": 123,
            "timestamp": 1604933340
        },
        {
            "operation": "debit",
            "amount": 123,
            "timestamp": 1604933340
        }
    ]
}
```

Both StartDate and EndDate are optional and can be partially defined. For the example above, is possible to define StartDate as "2020-02" and EndDate as "2020-03".

When is necessary to get all the history of 2019, just define StartDate as "2019" and EndDate as "2019".

When is necessary to get all the history since February 2020 at now, just define StartDate as "2020-02" and EndDate as "".

**Comment by alexandreliberato** [comment]
@alexgarzao I can work on this issue :)
May you assign it to me?

**Comment by juceliofloresta** [comment]
Hi @alexandreliberato, I appreciate the disposition.
I'm working in this issue right now.
