### ISSUE TITLE
Synthetic account reports

### ISSUE THREAD

**Issue by alexgarzao** [stone-co/the-amazing-ledger#34]
For the reports, we are assuming that we will have the following structure in the accounts: "class:group:subgroup:id", where "id" is free text.

We can have summary reports at the class, group, subgroup, and id level. In addition, a filter by date can be informed. Date must be expressed in ISO 8601 format: "YYYY-MM-DD".

Report calls receive an ACCOUNT PATH as an argument, which could be:

- Empty
- Class only (liability or ...)
- Class + group
- Class + group + sub-group
- Class + group + sub-group + ID

Example 1: Call to report without defining an ACCOUNT PATH (empty), during February 2020 and April 2020. StartDate is equal to "2020-02-01" and EndDate is equal to "2020-03-31".

Representation of the return in JSON format, just as an example:
```
{
    "total_credit": 600,
    "total_debit": 800,
    paths: [
        {
            "account_path": "liability",
            "credit": 200,
            "debit": 300
        },
        {
            "account_path": "assets",
            "credit": 400,
            "debit": 500
        }
    ]
}
```

Example 2: Call for report defining ACCOUNT PATH as liability

Representation of the return in JSON format, just as an example:
```
{
    "total_credit": 600,
    "total_debit": 800,
    paths: [
        {
            "account_path": "liability:ted_in",
            "credit": 200,
            "debit": 300
        },
        {
            "account_path": "liability:clients",
            "credit": 400,
            "debit": 500
        }
    ]
}
```

Both StartDate and EndDate are optional and can be partially defined. For the example above, is possible to define StartDate as "2020-02" and EndDate as "2020-03".

When is necessary to get all the history of 2019, just define StartDate as "2019" and EndDate as "2019".

When is necessary to get all the history since February 2020 at now, just define StartDate as "2020-02" and EndDate as "".

**Comment by alexandreliberato** [comment]
I can get this one @alexgarzao

**Comment by alexandreliberato** [comment]
As client I want to retrieve summary reports by the following levels:

 - class
 - group
 - subgroup
 - id

arguments: string (account path variations)
filters: date (YYYY-MM-DD) * 

eg: 

a) accPath = "liability:clients", startDate = "2020-02-01" and endDate = "2020-03-31".

**Comment by alexgarzao** [comment]
Yep. It seems to be ok.

**Comment by alexgarzao** [comment]
Hello @alexandreliberato . Any news?

**Comment by alexandreliberato** [comment]
I`m working on it right now.

**Comment by alexandreliberato** [comment]
Sorry about the delay, almost finishing it :)

**Comment by alexandreliberato** [comment]
If the account path is empty the system should return the summary by class level.
If the account path contains the class the system should return the summary by group level.
@alexgarzao, is that right?

**Comment by alexgarzao** [comment]
I'm so sorry about the delay...

Yep, you are right.

**Comment by alexandreliberato** [comment]
@alexgarzao @guilhermebr I'm receiving an error about context in the unit test, as I'm not used to the language maybe I could get some help? I was thinking about a call, what does you think?

**Comment by alexandreliberato** [comment]
You can check my branch here: https://github.com/alexandreliberato/the-amazing-ledger/tree/feat/issue-34 :)

**Comment by victoraugustolls** [comment]
Replaced by #96
