### ISSUE TITLE
New proposal for the project structure

### ISSUE THREAD

**Issue by juceliofloresta** [stone-co/the-amazing-ledger#47]
The idea here is to just start the discussion about the new project structure.

We starting with a structure more `flat` where we're removing `/pkg/command-handler` and `/pkg/command-handler/domain/ledger` and introduces the `value objects` concept from DDD.

### Structure Proposal
```
├── pkg
│   ├── common
│   │   └── configuration
│   │       └── config.go
│   ├── domain
│   │   ├── entities
│   │   │   ├── cached_accounts.go
│   │   │   ├── cached_accounts_test.go
│   │   │   ├── entry.go
│   │   │   ├── entry_test.go
│   │   │   ├── transaction.go
│   │   │   └── transaction_test.go
│   │   ├── errors.go
│   │   ├── repository.go
│   │   ├── repository_mock.go
│   │   ├── transactions_mock.go
│   │   ├── usecase
│   │   │   ├── create_transaction.go
│   │   │   ├── create_transaction_test.go
│   │   │   ├── get_account_balance.go
│   │   │   ├── get_account_balance_test.go
│   │   │   ├── get_last_version.go
│   │   │   ├── ledger.go
│   │   │   ├── load_objects_into_cache.go
│   │   │   ├── load_objects_into_cache_test.go
│   │   │   └── setup_test.go
│   │   ├── usecase.go
│   │   └── vo 
│   │       ├── account_balance.go
│   │       ├── account_balance_test.go
│   │       ├── account_class.go
│   │       ├── account_class_test.go
│   │       ├── account_name.go
│   │       ├── account_name_test.go
│   │       ├── operation_type.go
│   │       ├── operation_type_test.go
│   │       ├── version.go
│   │       └── version_test.go
```
vo =  Value Objects (DDD)

### Older structure:
```
├── pkg
│   ├── command-handler
│   │   └── domain
│   │       └── ledger
│   │           ├── entities
│   │           │   ├── account_balance.go
│   │           │   ├── account_balance_test.go
│   │           │   ├── account_class.go
│   │           │   ├── account_class_test.go
│   │           │   ├── account_name.go
│   │           │   ├── account_name_test.go
│   │           │   ├── cached_accounts.go
│   │           │   ├── cached_accounts_test.go
│   │           │   ├── entry.go
│   │           │   ├── entry_test.go
│   │           │   ├── errors.go
│   │           │   ├── operation_type.go
│   │           │   ├── operation_type_test.go
│   │           │   ├── transaction.go
│   │           │   ├── transaction_test.go
│   │           │   ├── version.go
│   │           │   └── version_test.go
│   │           ├── repository.go
│   │           ├── repository_mock.go
│   │           ├── transactions_mock.go
│   │           ├── usecase
│   │           │   ├── create_transaction.go
│   │           │   ├── create_transaction_test.go
│   │           │   ├── get_account_balance.go
│   │           │   ├── get_account_balance_test.go
│   │           │   ├── get_last_version.go
│   │           │   ├── ledger.go
│   │           │   ├── load_objects_into_cache.go
│   │           │   ├── load_objects_into_cache_test.go
│   │           │   └── setup_test.go
│   │           └── usecase.go
```

**Comment by alexrios** [comment]
Since the _V0_ is not finished yet, what problem we are trying to solve with this suggestion?
I'm asking this to give an opinion aiming at the same thing.

**Comment by juceliofloresta** [comment]
I agree with you that we can do this before the release of _V0_.

Opening this issue I would like to see your opinion and receive other suggestions in different project folders, structures, in addition to this proposal.

**Comment by alexgarzao** [comment]
IMHO, the idea here is to be more "compliant" with a clean architecture. In our current structure, there ate two folders without files. We can organize in a way to be more "flat" and clean out the structure.

In the same way, with DDD in mind, I think that is a good thing to split between value objects and entities.

**Comment by alexrios** [comment]
> I agree with you that we can do this before the release of _V0_.

After* 😅

**Comment by alexrios** [comment]
> ... the idea here is to be more "compliant" with a clean architecture. 
Why does the project need to be compliant with this architecture?
Note: Clean Architecture is just a mental model / specification, not really a set of naming conventions. These conventions exists on implementations of clean architecture, such as: Hexagonal, SCREAM and so on.

> In our current structure, there are two folders without files. 
I agree. It does not make sense.

> We can organize in a way to be more "flat" and clean out the structure.
I agree with you.
 
> In the same way, with DDD in mind, I think that is a good thing to split between value objects and entities.
Why do you think it is a good thing? Could you , by any chance, share what trade offs you have envisioning?

**Comment by alexgarzao** [comment]
| Why do you think it is a good thing? Could you , by any chance, share what trade offs you have envisioning?

At this time, in the Ledger, I would like to just be more clear about the difference between entity and value object in our project structure.  I think that it's not a "must have", but a "good to have" thing. And is easier to do this :-)

If someone would like to read about the difference between entities and value objects, here (https://www.infoq.com/minibooks/domain-driven-design-quickly/) there is a resume (page 34 in PDF format).

Just two points:

1) Some time ago, I worked on a project that we split between entities and value objects. With this simple organization, was a lot easier to understand the project (to people who understand a little about DDD, of course).

2) Some time ago, I asked you about best practices (in Go) when I must return a pointer or a value in a New func. Thinking a bit more, my feeling is that in the case of value objects, we need to return by value, and in the case of an entity, return a pointer. And splitting between entities and VO turns easy to understand about this "rule".

**Comment by alexrios** [comment]
@alexgarzao 
> clear about the difference between entity and value object in our project structure.

Ok. I won't iterate more over this. We're anticipating a clarity problem not really solving an actual issue.

> Some time ago, I asked you about best practices (in Go) when I must return a pointer or a value ....

I don't agree with it but this a discussion is out of the current issue scope. We can discuss it on another forum.

Besides, I would like to suggest to drop the _legacy naming convention on package_ (pre-modules) `pkg` and rename it with anything more cohesive, for example `app`. The ideia behind that is to create a namespace which could make a clear distinction between source code and from configuration files and other project stuff.

Since we're trying to remove the clumsy project structure we could either move `config.go` under `app` folder. It seems reasonable because all the configuration are from the `app`.

**Comment by alexgarzao** [comment]
> Besides, I would like to suggest to drop the _legacy naming convention on package_ (pre-modules) `pkg` and rename it with anything more cohesive, for example `app`. The ideia behind that is to create a namespace which could make a clear distinction between source code and from configuration files and other project stuff.

LTGM.

> Since we're trying to remove the clumsy project structure we could either move `config.go` under `app` folder. It seems reasonable because all the configuration are from the `app`.

At this time, 'config.go' is under '/pkg/common/configuration/config.go'. WDYT about move to '/app/config/config.go'? Or just '/app/config.go'?

**Comment by alexrios** [comment]
> At this time, 'config.go' is under '/pkg/common/configuration/config.go'. WDYT about move to '/app/config/config.go'? Or just '/app/config.go'?

`app/config.go`. From the client perspective: `app.LoadConfig()`

**Comment by alexgarzao** [comment]
Agree :-)

**Comment by alexrios** [comment]
There is an issue separating VO and Entities.

consider this dir tree:

```
├── app
│   ├── domain
│   │   ├── entitities
│   │   ├── usecase
│   │   └── vo 
```


Since any file in `usecase` can use both `entities` and `vo` AND `vo` will probably use `entities`, circular dependencies will raises.

Suggestions:
1 - **Do nothing** and keep VOs and Entities together. take into account that this separation does not solve a real problem. and the project **is not even stable** (V0).
2 - Make it more modular yet.
```
├── entities
│   ├── entry
│   │   ├── usecase // implementations of usecase interface below.
│   │   ├── usecases.go
│   │   ├──  repositories.go 
.....
├── vo
│   ├── account_class // same as above.
```

@juceliofloresta @alexgarzao thoughts?

**Comment by alexgarzao** [comment]
Just to try to clarify, I will use some terms that we aren't using in this project.

VO is an "elementary thing", like string, CPF, CNPJ, Address, UUID, ID, Name, Birthdate, and so on.

Entities are somethings "more complex" like Account, purchase, transfer, ...

In this case, it's ok an entity use a VO, and is OK for a VO to use another VO. But a VO cannot use an entity.

**Comment by alexrios** [comment]
@alexgarzao The issue here is about cyclic dependency.

**Comment by alexandreliberato** [comment]
> There is an issue separating VO and Entities.
> 
> consider this dir tree:
> 
> ```
> ├── app
> │   ├── domain
> │   │   ├── entitities
> │   │   ├── usecase
> │   │   └── vo 
> ```
> 
> Since any file in `usecase` can use both `entities` and `vo` AND `entities` will probably use `vo`, circular dependencies will raises.
> 
> Suggestions:
> 1 - **Do nothing** and keep VOs and Entities together. take into account that this separation does not solve a real problem. and the project **is not even stable** (V0).
> 2 - Make it more modular yet.
> 
> ```
> ├── entities
> │   ├── entry
> │   │   ├── usecase // implementations of usecase interface below.
> │   │   ├── usecases.go
> │   │   ├──  repositories.go 
> .....
> ├── vo
> │   ├── account_class // same as above.
> ```
> 
> @juceliofloresta @alexgarzao thoughts?

I would go with the first option, leave the possible problem to solve when it arises.
Is the structure propose missing the 'gateways' directory? Or maybe I am missing something haha

**Comment by alexrios** [comment]
@alexandreliberato the trees on @juceliofloresta's examples are a subset of the real project tree for the sake of comparison.

**Comment by juceliofloresta** [comment]
If `usecase` import `entities` or `value objects` and `entities` import ` value objects` does this raise a circular dependency?

```
Usecase.Entities.valueObjects
Usecae.ValueObjects

// never
Usecase.ValueObjects.Entities
```

**Comment by alexrios** [comment]
> If `usecase` import `entities` or `value objects` and `entities` import ` value objects` does this raise a circular dependency?
> 
> ```
> Usecase.Entities.valueObjects
> Usecae.ValueObjects
> 
> // never
> Usecase.ValueObjects.Entities
> ```

Yes it does, because of the returned errors. Try and see whenever you can 🍽️

**Comment by alexgarzao** [comment]
> @alexgarzao The issue here is about cyclic dependency.

Yep, I got it. But, as @juceliofloresta said, I think that it cannot do a circular reference.

IMHO, errors must be defined inside the domain package, together with the interfaces to the use case, the repository, ...

**Comment by alexrios** [comment]
Given '-> ' as  'imports'

usecase implementation -> entitiy, vo, domain (errors)
entitty -> vo, domain (errors)
vo -> (nothing)

circular dependencies: 

- domain (usecase) -> entity (Transaction) -> domain (errors)
- domain (usecase) -> vo (version) -> domain (errors)
