### ISSUE TITLE
Proposal: Biweekly Community Meeting

### ISSUE THREAD

**Issue by alexrios** [stone-co/the-amazing-ledger#53]
WDYT about to setup a biweekly call to discuss the project roadmap and other subjects?
We can elaborate and narrow down the meeting scope in this issue here.

@alexandreliberato @alexgarzao @juceliofloresta @guilhermebr

**Comment by alexandreliberato** [comment]
It is a good idea I think it can be used to accelerate the project pace and make the scope clear too.

**Comment by alexrios** [comment]
@alexandreliberato additionally this initiative could create 2 things:
 - A list of action items 
 - Architecture decisions

also save these informations on some place to further searches (wiki maybe?)

**Comment by alexgarzao** [comment]
I think that it's a great idea :-)

I know that it's wrong but, at this time, we have just a bit of documentation. And a lot of things are just in our minds (Stone team).

These meetings are a great opportunity to try to clarify a bit more about the project.

To registry architecture decisions, we are thinking about to use ADR (architecture decisions record). It's simple but very interesting :-)

**Comment by alexrios** [comment]
> To registry architecture decisions, we are thinking about to use ADR

Probably I'm the most annoying person when the topic is **trade offs**. Every time I ask questions like: **why?**, **what is the intent?**, **what problem it solves?** and so on, is to "force" the contributors to make clear the decisions made previously and write them down. In that way, we put the conversation out of the _opinions bubble_. 

Using ADR or just writing the motivations in the wiki are both the same for me. I'm down with any method chosen, what cannot happen is to continue creating blind spots.

**Comment by alexgarzao** [comment]
> Probably I'm the most annoying person when the topic is **trade offs**. Every time I ask questions like: **why?**, **what is the intent?**, **what problem it solves?** and so on, is to "force" the contributors to make clear the decisions made previously and write them down. In that way, we put the conversation out of the _opinions bubble_.

IMHO, it's a "good thing".

Why ADR? What problem does it solve? We need to registry all architecture decisions. For example, why we are using Postgres? Why are not using a NoSQL database? Why CQRS and event sourcing? Why optimistic lock? Why pub/sub between internal components? ...

Besides that, ADR is a clear (and simple) way. We can use a wiki, a simple text file, or better, an MD file. And putting all ADR's on the repo, all decisions are versioned with the code. We can check out an older version and see the code and the ADR's at that time.

> Using ADR or just writing the motivations in the wiki are both the same for me. I'm down with any method chosen, what cannot happen is to continue creating blind spots.

About blind spots, I agree. We are trying to improve a lot of things. I think that this community meeting is an "easy way" to share our vision, roadmap, and so on.

**Comment by alexrios** [comment]
Any chance to have this meeting this year? @alexandreliberato @alexgarzao @juceliofloresta @guilhermebr

**Comment by alexandreliberato** [comment]
I'm in!

**Comment by juceliofloresta** [comment]
I think that is better on January 7th 

What do you expect from this meeting?
- roadmap?
- project vision?
- architecture?
- ...?

**Comment by alexandreliberato** [comment]
Besides the already mentioned motivations above, I think that it could helps to clear some points that would take too many text messages to settle. 

-   A clear scope
-   A list of action items
-   Architecture decisions

**Comment by alexrios** [comment]
will it still happen tomorrow?

**Comment by alexrios** [comment]
I'm closing this issue due the inactivity.

**Comment by victoraugustolls** [comment]
@alexrios if you still have interest on this, I would like it very much :)

**Comment by alexrios** [comment]
I'm down! please, don't drop the ball once again folks 🏈

**Comment by victoraugustolls** [comment]
@alexrios count on me! I'll open a discussion for this
