### ISSUE TITLE
Basic reporting RPC

### ISSUE THREAD

**Issue by victoraugustolls** [stone-co/the-amazing-ledger#96]
We should provide a basic method for extracting reports and, based on previous discussions, it should be something like:

Request:

```json
{
    "path": "liability.accounts.*",
    "level": 3,
    "start_date": "2020-03-09T22:18:26.625Z",
    "end_date": "2020-03-09T22:18:26.625Z"
}
```

- Path should be the only required parameter
- If no level is sent, defaults to the number of levels in the path (3 in the example)
- start date and end date should be optional

Response:

```json
{
    "credit": 600,
    "debit": 800,
    "accounts": [
        {
            "path": "liability",
            "credit": 200,
            "debit": 300
        },
        {
            "path": "assets",
            "credit": 400,
            "debit": 500
        }
    ]
}
```

**Comment by alexandreliberato** [comment]
Working on it!
